// =====================================
// QUESTIONS.JS
// =====================================

const questions = [
  // ===== PLANT BIOLOGY =====
  { q:'Photosynthesis occurs in:', opts:['Nucleus','Chloroplast','Ribosome','Vacuole'], ans:1 },
  { q:'Water is transported through:', opts:['Phloem','Xylem','Cortex','Cambium'], ans:1 },
  { q:'The green pigment in plants is:', opts:['Chlorophyll','Melanin','Hemoglobin','Carotene'], ans:0 },
  { q:'Potato is a modified:', opts:['Root','Stem','Leaf','Fruit'], ans:1 },
  { q:'Mendel worked on:', opts:['Rice','Wheat','Pea','Maize'], ans:2 },
  { q:'Study of fungi is called:', opts:['Ecology','Cytology','Mycology','Genetics'], ans:2 },
  { q:'Food is transported by:', opts:['Xylem','Phloem','Epidermis','Cortex'], ans:1 },
  { q:'Cell wall is mainly made of:', opts:['Chitin','Cellulose','Protein','Lipid'], ans:1 },
  { q:'Double fertilization occurs in:', opts:['Bryophytes','Gymnosperms','Angiosperms','Pteridophytes'], ans:2 },
  { q:'Sporopollenin is present in:', opts:['Ovule','Seed coat','Pollen wall','Endoderm'], ans:2 },
  { q:'Coconut water is:', opts:['Embryo','Endosperm','Cotyledon','Pericarp'], ans:1 },
  { q:'Which is a C4 plant?', opts:['Rice','Wheat','Maize','Potato'], ans:2 },
  { q:'Nitrogen fixation in legumes is carried out by:', opts:['Yeast','Rhizobium','Amoeba','Algae'], ans:1 },
  { q:'Guard cells regulate:', opts:['Respiration','Germination','Stomatal opening','Reproduction'], ans:2 },
  { q:'The edible part of mango is:', opts:['Endocarp','Mesocarp','Seed','Epicarp'], ans:1 },
  { q:'ATP is known as:', opts:['Hormone','Enzyme','Energy Currency','Pigment'], ans:2 },
  { q:'Bryophytes are called:', opts:['Flowering Plants','Amphibians of Plant Kingdom','Seed Plants','Vascular Plants'], ans:1 },
  { q:'First stable product of Calvin cycle is:', opts:['OAA','PEP','PGA','RuBP'], ans:2 },
  { q:'Casparian strips occur in:', opts:['Cortex','Epidermis','Endodermis','Pericycle'], ans:2 },
  { q:'Enzyme responsible for CO2 fixation:', opts:['Catalase','ATPase','Rubisco','Amylase'], ans:2 },
  { q:'Crossing over occurs during:', opts:['Leptotene','Zygotene','Pachytene','Diplotene'], ans:2 },
  { q:'Aleurone layer is rich in:', opts:['Lipids','Proteins','DNA','Cellulose'], ans:1 },
  { q:'Water potential of pure water is:', opts:['+1','-1','0','100'], ans:2 },
  { q:'Double fertilization was discovered by:', opts:['Mendel','Darwin','Nawaschin','Lamarck'], ans:2 },
  { q:'Pleiotropy means:', opts:['One trait controlled by many genes','One gene controls many traits','Linked genes','Multiple alleles'], ans:1 },

  // ===== HUMAN BIOLOGY =====
  { q:'Functional unit of kidney:', opts:['Neuron','Nephron','Alveolus','Osteon'], ans:1 },
  { q:'Human heart has:', opts:['2 chambers','3 chambers','4 chambers','5 chambers'], ans:2 },
  { q:'Oxygen carrying pigment in blood:', opts:['Keratin','Hemoglobin','Melanin','Myosin'], ans:1 },
  { q:'Insulin is secreted by:', opts:['Liver','Pancreas','Thyroid','Kidney'], ans:1 },
  { q:'Human chromosome number:', opts:['44','45','46','48'], ans:2 },
  { q:'Largest gland in body:', opts:['Thyroid','Liver','Pancreas','Pituitary'], ans:1 },
  { q:'Study of animals is:', opts:['Botany','Zoology','Ecology','Genetics'], ans:1 },
  { q:'Basic unit of life:', opts:['Tissue','Organ','Cell','Organ System'], ans:2 },
  { q:'Pacemaker of heart:', opts:['AV Node','SA Node','Bundle of His','Purkinje Fibres'], ans:1 },
  { q:'Universal recipient blood group:', opts:['O-','A+','B+','AB+'], ans:3 },
  { q:'Site of fertilization in humans:', opts:['Ovary','Uterus','Fallopian Tube','Vagina'], ans:2 },
  { q:'Antibodies are produced by:', opts:['RBC','Platelets','Lymphocytes','Plasma'], ans:2 },
  { q:'Human sperm is:', opts:['Diploid','Haploid','Triploid','Tetraploid'], ans:1 },
  { q:'Vitamin D deficiency causes:', opts:['Scurvy','Beriberi','Rickets','Pellagra'], ans:2 },
  { q:'Largest bone in human body:', opts:['Tibia','Radius','Femur','Humerus'], ans:2 },
  { q:'Smallest bone in human body:', opts:['Stapes','Malleus','Incus','Ulna'], ans:0 },
  { q:'Growth hormone is secreted by:', opts:['Thyroid','Pituitary','Pancreas','Adrenal'], ans:1 },
  { q:'Acrosome is derived from:', opts:['Nucleus','Mitochondria','Golgi Apparatus','Ribosome'], ans:2 },
  { q:'Immunoglobulin crossing placenta:', opts:['IgA','IgM','IgG','IgE'], ans:2 },
  { q:'Respiratory centre is located in:', opts:['Cerebrum','Cerebellum','Medulla Oblongata','Hypothalamus'], ans:2 },
  { q:'Sertoli cells are present in:', opts:['Ovary','Kidney','Testis','Liver'], ans:2 },
  { q:'Synapsis occurs during:', opts:['Mitosis','Meiosis I','Meiosis II','Cytokinesis'], ans:1 },
  { q:'Rh factor was discovered by:', opts:['Watson','Mendel','Landsteiner & Wiener','Darwin'], ans:2 },
  { q:'Hormone that lowers blood calcium:', opts:['PTH','Calcitonin','Insulin','Adrenaline'], ans:1 },
  { q:'First heart sound is due to closure of:', opts:['Semilunar Valves','AV Valves','Aortic Valve','Pulmonary Valve'], ans:1 }
];